version: '3.3'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'mohannad'
      MYSQL_PASSWORD: 'mohannadsecretpassword'
      MYSQL_ROOT_PASSWORD: 'rootsecretpassword'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

  springboot-app:
    build: .
    container_name: springboot-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/db
      SPRING_DATASOURCE_USERNAME: 'mohannad'
      SPRING_DATASOURCE_PASSWORD: 'mohannadsecretpassword'

volumes:
  my-db:
